INSERT INTO pokemonCard (id, name, type)
VALUES 
(1, 'Bulbasaur', 'Grass/Poison', 1),
(2, 'Ivysaur', 'Grass/Poison', 1),
(3, 'Venusaur', 'Grass/Poison', 1),
(4, 'Charmander', 'Fire', 1),
(5, 'Charmeleon', 'Fire', 1),
(6, 'Charizard', 'Fire/Flying', 1),
(7, 'Squirtle', 'Water', 1),
(8, 'Wartortle', 'Water', 1),
(9, 'Blastoise', 'Water', 1),
(10, 'Caterpie', 'Bug', 1),
(11, 'Metapod', 'Bug', 1),
(12, 'Butterfree', 'Bug/Flying', 1),
(13, 'Weedle', 'Bug/Poison', 1),
(14, 'Kakuna', 'Bug/Poison', 1),
(15, 'Beedrill', 'Bug/Poison', 1),
(16, 'Pidgey', 'Normal/Flying', 1),
(17, 'Pidgeotto', 'Normal/Flying', 1),
(18, 'Pidgeot', 'Normal/Flying', 1),
(19, 'Rattata', 'Normal', 1),
(20, 'Raticate', 'Normal', 1),
(21, 'Spearow', 'Normal/Flying', 1),
(22, 'Fearow', 'Normal/Flying', 1),
(23, 'Ekans', 'Poison', 1),
(24, 'Arbok', 'Poison', 1),
(25, 'Pikachu', 'Electric', 1),
(26, 'Raichu', 'Electric', 1);
